# Form implementation generated from reading ui file 'c:\Users\Umarov\desktop\projects\plotter\plotter\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.entries = EntryTableWidget(self.splitter)
        self.entries.setObjectName("entries")
        self.entries.setColumnCount(2)
        self.entries.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.entries.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.entries.setHorizontalHeaderItem(1, item)
        self.canvas = QtWidgets.QWidget(self.splitter)
        self.canvas.setObjectName("canvas")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_files = QtGui.QAction(MainWindow)
        self.open_files.setObjectName("open_files")
        self.open_folder = QtGui.QAction(MainWindow)
        self.open_folder.setObjectName("open_folder")
        self.exit_app = QtGui.QAction(MainWindow)
        self.exit_app.setObjectName("exit_app")
        self.add_files = QtGui.QAction(MainWindow)
        self.add_files.setObjectName("add_files")
        self.add_folder = QtGui.QAction(MainWindow)
        self.add_folder.setObjectName("add_folder")
        self.file.addAction(self.open_files)
        self.file.addAction(self.open_folder)
        self.file.addAction(self.add_files)
        self.file.addAction(self.add_folder)
        self.file.addSeparator()
        self.file.addAction(self.exit_app)
        self.menubar.addAction(self.file.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.entries.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Запись"))
        self.file.setTitle(_translate("MainWindow", "Файл"))
        self.open_files.setText(_translate("MainWindow", "Октрыть файлы..."))
        self.open_files.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.open_folder.setText(_translate("MainWindow", "Открыть папку..."))
        self.open_folder.setShortcut(_translate("MainWindow", "Ctrl+K, Ctrl+O"))
        self.exit_app.setText(_translate("MainWindow", "Выход"))
        self.add_files.setText(_translate("MainWindow", "Добавить файлы..."))
        self.add_folder.setText(_translate("MainWindow", "Добавить папку..."))
from .entry_table_widget import EntryTableWidget
